language: cpp
os: linux
sudo: required
dist: trusty
compiler: gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-dev
script: make debug; make release
notifications:
    email:
        recipients: aijunbai@gmail.com
        on_success: change
        on_failure: always

